/**
 * Stable API error codes — translated on mobile via AppLocalizations.
 * Keep `message` in French for backward compatibility with older app versions.
 */
const ErrorCodes = {
  // Auth / session
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  SESSION_REQUIRED: 'SESSION_REQUIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_INACTIVE: 'SESSION_INACTIVE',

  // Password reset / OTP
  INVALID_PHONE: 'INVALID_PHONE',
  APP_REQUIRED: 'APP_REQUIRED',
  ACCOUNT_AMBIGUOUS: 'ACCOUNT_AMBIGUOUS',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  OTP_SEND_FAILED: 'OTP_SEND_FAILED',
  MISSING_FIELDS: 'MISSING_FIELDS',
  OTP_INVALID_OR_EXPIRED: 'OTP_INVALID_OR_EXPIRED',
  DEVICE_MISMATCH: 'DEVICE_MISMATCH',
  REQUEST_INVALID: 'REQUEST_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_INCORRECT: 'OTP_INCORRECT',
  VERIFY_FIRST: 'VERIFY_FIRST',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_UPDATE_FAILED: 'PASSWORD_UPDATE_FAILED',

  // Common HTTP
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  ACCESS_DENIED: 'ACCESS_DENIED',
  NOT_FOUND: 'NOT_FOUND',

  // User profile
  NO_UPDATE_DATA: 'NO_UPDATE_DATA',
  DESCRIPTION_TOO_LONG: 'DESCRIPTION_TOO_LONG',
  USER_INCOMPLETE: 'USER_INCOMPLETE',
  VENDEUR_TYPE_SELLERS_ONLY: 'VENDEUR_TYPE_SELLERS_ONLY',
  VENDEUR_TYPE_INVALID: 'VENDEUR_TYPE_INVALID',
  PHONE_ALREADY_USED: 'PHONE_ALREADY_USED',
  PHONE_AMBIGUOUS: 'PHONE_AMBIGUOUS',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  FIREBASE_EMAIL_SYNC_FAILED: 'FIREBASE_EMAIL_SYNC_FAILED',

  // Transitaire gallery
  GALLERY_TRANSITAIRE_ONLY: 'GALLERY_TRANSITAIRE_ONLY',
  GALLERY_MUST_BE_ARRAY: 'GALLERY_MUST_BE_ARRAY',
  GALLERY_MAX_ITEMS: 'GALLERY_MAX_ITEMS',
  GALLERY_INVALID_ITEM: 'GALLERY_INVALID_ITEM',
  GALLERY_ITEM_TYPE_URL: 'GALLERY_ITEM_TYPE_URL',

  // Misc user actions
  FCM_TOKEN_REQUIRED: 'FCM_TOKEN_REQUIRED',
  ARTICLE_ID_REQUIRED: 'ARTICLE_ID_REQUIRED',
  FILE_REQUIRED: 'FILE_REQUIRED',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // CAPTCHA
  CAPTCHA_INVALID: 'CAPTCHA_INVALID',
  CAPTCHA_TOKEN_MISSING: 'CAPTCHA_TOKEN_MISSING',
  CAPTCHA_ERROR: 'CAPTCHA_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  // Transitaire verification
  TRANSITAIRE_ONLY: 'TRANSITAIRE_ONLY',
  TRANSITAIRE_VERIF_ALREADY_VERIFIED: 'TRANSITAIRE_VERIF_ALREADY_VERIFIED',
  TRANSITAIRE_VERIF_PENDING: 'TRANSITAIRE_VERIF_PENDING',
  TRANSITAIRE_VERIF_CARDS_REQUIRED: 'TRANSITAIRE_VERIF_CARDS_REQUIRED',
  TRANSITAIRE_VERIF_COMPANY_REQUIRED: 'TRANSITAIRE_VERIF_COMPANY_REQUIRED',
  TRANSITAIRE_VERIF_REFERENCE_PHONE_INVALID: 'TRANSITAIRE_VERIF_REFERENCE_PHONE_INVALID',
  TRANSITAIRE_VERIF_SAVE_FAILED: 'TRANSITAIRE_VERIF_SAVE_FAILED',
  TRANSITAIRE_VERIF_SUBMIT_SUCCESS: 'TRANSITAIRE_VERIF_SUBMIT_SUCCESS',
  TRANSITAIRE_VERIF_SUBMIT_FAILED: 'TRANSITAIRE_VERIF_SUBMIT_FAILED',
  TRANSITAIRE_VERIF_STATUS_FAILED: 'TRANSITAIRE_VERIF_STATUS_FAILED',
  TRANSITAIRE_VERIF_LIST_FAILED: 'TRANSITAIRE_VERIF_LIST_FAILED',
  TRANSITAIRE_VERIF_DETAIL_FAILED: 'TRANSITAIRE_VERIF_DETAIL_FAILED',
  TRANSITAIRE_VERIF_NOT_FOUND: 'TRANSITAIRE_VERIF_NOT_FOUND',
  TRANSITAIRE_VERIF_APPROVE_INVALID: 'TRANSITAIRE_VERIF_APPROVE_INVALID',
  TRANSITAIRE_VERIF_DOCS_MISSING: 'TRANSITAIRE_VERIF_DOCS_MISSING',
  TRANSITAIRE_VERIF_APPROVE_SUCCESS: 'TRANSITAIRE_VERIF_APPROVE_SUCCESS',
  TRANSITAIRE_VERIF_APPROVE_FAILED: 'TRANSITAIRE_VERIF_APPROVE_FAILED',
  TRANSITAIRE_VERIF_REJECT_MOTIF_REQUIRED: 'TRANSITAIRE_VERIF_REJECT_MOTIF_REQUIRED',
  TRANSITAIRE_VERIF_REJECT_INVALID: 'TRANSITAIRE_VERIF_REJECT_INVALID',
  TRANSITAIRE_VERIF_REJECT_SUCCESS: 'TRANSITAIRE_VERIF_REJECT_SUCCESS',
  TRANSITAIRE_VERIF_REJECT_FAILED: 'TRANSITAIRE_VERIF_REJECT_FAILED',
};

module.exports = ErrorCodes;
