/**
 * Stable API error codes — translated on mobile via AppLocalizations.
 * Keep `message` in French for backward compatibility with older app versions.
 */
const ErrorCodes = {
  // Auth / session
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  SESSION_REQUIRED: 'SESSION_REQUIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_INACTIVE: 'SESSION_INACTIVE',

  // Password reset / OTP
  INVALID_PHONE: 'INVALID_PHONE',
  APP_REQUIRED: 'APP_REQUIRED',
  ACCOUNT_AMBIGUOUS: 'ACCOUNT_AMBIGUOUS',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  OTP_SEND_FAILED: 'OTP_SEND_FAILED',
  MISSING_FIELDS: 'MISSING_FIELDS',
  OTP_INVALID_OR_EXPIRED: 'OTP_INVALID_OR_EXPIRED',
  DEVICE_MISMATCH: 'DEVICE_MISMATCH',
  REQUEST_INVALID: 'REQUEST_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_INCORRECT: 'OTP_INCORRECT',
  VERIFY_FIRST: 'VERIFY_FIRST',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_UPDATE_FAILED: 'PASSWORD_UPDATE_FAILED',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};

module.exports = ErrorCodes;
